# Generated by Django 3.2.7 on 2025-02-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='red_table',
            new_name='reg_table',
        ),
    ]
