# Generated by Django 3.1.2 on 2025-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_rename_red_table_reg_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=150)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='reg_table',
            new_name='Register',
        ),
    ]
